#ifndef COPILOT_TYPES_H
#define COPILOT_TYPES_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdbool.h>
#include <stdint.h>

// Copilot C99 backend header (generated by RiTMOS)
#include "copilot.h"

#ifdef __cplusplus
} // extern "C"
#endif

#endif // COPILOT_TYPES_H
