extern double battery_soc;
extern bool obstacle_front;
extern bool obstacle_left;
extern bool obstacle_right;
extern bool at_science_rock;
extern bool battery_near_outpost;
extern double cmd_vel_lin;
void handlerMR_011_MAINTAIN_SPEED_WHEN_FULL_BATTERY(void);
void handlerMR_009_RETURN_TO_OUTPOST_ON_LOW_BATTERY(void);
void step(void);
