/*
 * Generated by Copilot via RiTMOS.
 * Annotated on: 2026-02-25T12:30:29
 *
 * This file implements a monitor automaton
 *   M = (S, Σ, s_init, δ, V)
 * where:
  *   - S is the set of monitor states, encoded by the static stream
 *     variables, counters, and their index variables.
 *   - Σ is the set of input symbols (valuations of the external input
 *     variables provided to the monitor).
 *   - s_init is the initial state, given by the static initialisers
 *     before the first call to step().
 *   - δ is the transition function S × Σ → S, implemented by the
 *     generator functions sN_gen() together with the body of step().
 *   - V is the set of verdict states (e.g., violation/alert states),
 *     detected by handler*_guard() functions, which trigger the
 *     corresponding handler*() callbacks.
 */


#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>

#include "copilot_types.h"
#include "copilot.h"

/* Input copies for the current step (one symbol σ ∈ Σ). */

static double battery_soc_cpy;
static bool obstacle_front_cpy;
static bool obstacle_left_cpy;
static bool obstacle_right_cpy;
static bool at_science_rock_cpy;
static bool battery_near_outpost_cpy;
static double cmd_vel_lin_cpy;

/* Internal streams: components of the monitor state S stored as ring buffers. */
static bool s0[(1)] = {(true)};
static bool s60[(1)] = {(false)};
static bool s59[(1)] = {(false)};
static bool s58[(1)] = {(false)};
static bool s57[(1)] = {(false)};
static bool s56[(1)] = {(false)};
static bool s55[(1)] = {(false)};
static bool s54[(1)] = {(false)};
static bool s53[(1)] = {(false)};
static bool s52[(1)] = {(false)};
static bool s51[(1)] = {(false)};
static bool s50[(1)] = {(false)};
static bool s49[(1)] = {(false)};
static bool s48[(1)] = {(false)};
static bool s47[(1)] = {(false)};
static bool s46[(1)] = {(false)};
static bool s45[(1)] = {(false)};
static bool s44[(1)] = {(false)};
static bool s43[(1)] = {(false)};
static bool s42[(1)] = {(false)};
static bool s41[(1)] = {(false)};
static bool s40[(1)] = {(false)};
static bool s39[(1)] = {(false)};
static bool s38[(1)] = {(false)};
static bool s37[(1)] = {(false)};
static bool s36[(1)] = {(false)};
static bool s35[(1)] = {(false)};
static bool s34[(1)] = {(false)};
static bool s33[(1)] = {(false)};
static bool s32[(1)] = {(false)};
static bool s31[(1)] = {(false)};
static bool s30[(1)] = {(false)};
static bool s29[(1)] = {(false)};
static bool s28[(1)] = {(false)};
static bool s27[(1)] = {(false)};
static bool s26[(1)] = {(false)};
static bool s25[(1)] = {(false)};
static bool s24[(1)] = {(false)};
static bool s23[(1)] = {(false)};
static bool s22[(1)] = {(false)};
static bool s21[(1)] = {(false)};
static bool s20[(1)] = {(false)};
static bool s19[(1)] = {(false)};
static bool s18[(1)] = {(false)};
static bool s17[(1)] = {(false)};
static bool s16[(1)] = {(false)};
static bool s15[(1)] = {(false)};
static bool s14[(1)] = {(false)};
static bool s13[(1)] = {(false)};
static bool s12[(1)] = {(false)};
static bool s11[(1)] = {(false)};
static bool s10[(1)] = {(false)};
static bool s9[(1)] = {(false)};
static bool s8[(1)] = {(false)};
static bool s7[(1)] = {(false)};
static bool s6[(1)] = {(false)};
static bool s5[(1)] = {(false)};
static bool s4[(1)] = {(false)};
static bool s3[(1)] = {(false)};
static bool s2[(1)] = {(false)};
static bool s1[(1)] = {(false)};
static int32_t s61[(1)] = {((int32_t)(0))};
static bool s62[(1)] = {(true)};
static int32_t s63[(1)] = {((int32_t)(0))};
static bool s64[(1)] = {(true)};

/* Stream indices for the ring buffers (history depth used by δ). */
static size_t s0_idx = (0);
static size_t s60_idx = (0);
static size_t s59_idx = (0);
static size_t s58_idx = (0);
static size_t s57_idx = (0);
static size_t s56_idx = (0);
static size_t s55_idx = (0);
static size_t s54_idx = (0);
static size_t s53_idx = (0);
static size_t s52_idx = (0);
static size_t s51_idx = (0);
static size_t s50_idx = (0);
static size_t s49_idx = (0);
static size_t s48_idx = (0);
static size_t s47_idx = (0);
static size_t s46_idx = (0);
static size_t s45_idx = (0);
static size_t s44_idx = (0);
static size_t s43_idx = (0);
static size_t s42_idx = (0);
static size_t s41_idx = (0);
static size_t s40_idx = (0);
static size_t s39_idx = (0);
static size_t s38_idx = (0);
static size_t s37_idx = (0);
static size_t s36_idx = (0);
static size_t s35_idx = (0);
static size_t s34_idx = (0);
static size_t s33_idx = (0);
static size_t s32_idx = (0);
static size_t s31_idx = (0);
static size_t s30_idx = (0);
static size_t s29_idx = (0);
static size_t s28_idx = (0);
static size_t s27_idx = (0);
static size_t s26_idx = (0);
static size_t s25_idx = (0);
static size_t s24_idx = (0);
static size_t s23_idx = (0);
static size_t s22_idx = (0);
static size_t s21_idx = (0);
static size_t s20_idx = (0);
static size_t s19_idx = (0);
static size_t s18_idx = (0);
static size_t s17_idx = (0);
static size_t s16_idx = (0);
static size_t s15_idx = (0);
static size_t s14_idx = (0);
static size_t s13_idx = (0);
static size_t s12_idx = (0);
static size_t s11_idx = (0);
static size_t s10_idx = (0);
static size_t s9_idx = (0);
static size_t s8_idx = (0);
static size_t s7_idx = (0);
static size_t s6_idx = (0);
static size_t s5_idx = (0);
static size_t s4_idx = (0);
static size_t s3_idx = (0);
static size_t s2_idx = (0);
static size_t s1_idx = (0);
static size_t s61_idx = (0);
static size_t s62_idx = (0);
static size_t s63_idx = (0);
static size_t s64_idx = (0);

/* Accessor functions sN_get(k): read previous stream values used by the transition function δ. */

static bool s0_get(size_t x) {
  return (s0)[((s0_idx) + (x)) % ((size_t)(1))];
}

static bool s60_get(size_t x) {
  return (s60)[((s60_idx) + (x)) % ((size_t)(1))];
}

static bool s59_get(size_t x) {
  return (s59)[((s59_idx) + (x)) % ((size_t)(1))];
}

static bool s58_get(size_t x) {
  return (s58)[((s58_idx) + (x)) % ((size_t)(1))];
}

static bool s57_get(size_t x) {
  return (s57)[((s57_idx) + (x)) % ((size_t)(1))];
}

static bool s56_get(size_t x) {
  return (s56)[((s56_idx) + (x)) % ((size_t)(1))];
}

static bool s55_get(size_t x) {
  return (s55)[((s55_idx) + (x)) % ((size_t)(1))];
}

static bool s54_get(size_t x) {
  return (s54)[((s54_idx) + (x)) % ((size_t)(1))];
}

static bool s53_get(size_t x) {
  return (s53)[((s53_idx) + (x)) % ((size_t)(1))];
}

static bool s52_get(size_t x) {
  return (s52)[((s52_idx) + (x)) % ((size_t)(1))];
}

static bool s51_get(size_t x) {
  return (s51)[((s51_idx) + (x)) % ((size_t)(1))];
}

static bool s50_get(size_t x) {
  return (s50)[((s50_idx) + (x)) % ((size_t)(1))];
}

static bool s49_get(size_t x) {
  return (s49)[((s49_idx) + (x)) % ((size_t)(1))];
}

static bool s48_get(size_t x) {
  return (s48)[((s48_idx) + (x)) % ((size_t)(1))];
}

static bool s47_get(size_t x) {
  return (s47)[((s47_idx) + (x)) % ((size_t)(1))];
}

static bool s46_get(size_t x) {
  return (s46)[((s46_idx) + (x)) % ((size_t)(1))];
}

static bool s45_get(size_t x) {
  return (s45)[((s45_idx) + (x)) % ((size_t)(1))];
}

static bool s44_get(size_t x) {
  return (s44)[((s44_idx) + (x)) % ((size_t)(1))];
}

static bool s43_get(size_t x) {
  return (s43)[((s43_idx) + (x)) % ((size_t)(1))];
}

static bool s42_get(size_t x) {
  return (s42)[((s42_idx) + (x)) % ((size_t)(1))];
}

static bool s41_get(size_t x) {
  return (s41)[((s41_idx) + (x)) % ((size_t)(1))];
}

static bool s40_get(size_t x) {
  return (s40)[((s40_idx) + (x)) % ((size_t)(1))];
}

static bool s39_get(size_t x) {
  return (s39)[((s39_idx) + (x)) % ((size_t)(1))];
}

static bool s38_get(size_t x) {
  return (s38)[((s38_idx) + (x)) % ((size_t)(1))];
}

static bool s37_get(size_t x) {
  return (s37)[((s37_idx) + (x)) % ((size_t)(1))];
}

static bool s36_get(size_t x) {
  return (s36)[((s36_idx) + (x)) % ((size_t)(1))];
}

static bool s35_get(size_t x) {
  return (s35)[((s35_idx) + (x)) % ((size_t)(1))];
}

static bool s34_get(size_t x) {
  return (s34)[((s34_idx) + (x)) % ((size_t)(1))];
}

static bool s33_get(size_t x) {
  return (s33)[((s33_idx) + (x)) % ((size_t)(1))];
}

static bool s32_get(size_t x) {
  return (s32)[((s32_idx) + (x)) % ((size_t)(1))];
}

static bool s31_get(size_t x) {
  return (s31)[((s31_idx) + (x)) % ((size_t)(1))];
}

static bool s30_get(size_t x) {
  return (s30)[((s30_idx) + (x)) % ((size_t)(1))];
}

static bool s29_get(size_t x) {
  return (s29)[((s29_idx) + (x)) % ((size_t)(1))];
}

static bool s28_get(size_t x) {
  return (s28)[((s28_idx) + (x)) % ((size_t)(1))];
}

static bool s27_get(size_t x) {
  return (s27)[((s27_idx) + (x)) % ((size_t)(1))];
}

static bool s26_get(size_t x) {
  return (s26)[((s26_idx) + (x)) % ((size_t)(1))];
}

static bool s25_get(size_t x) {
  return (s25)[((s25_idx) + (x)) % ((size_t)(1))];
}

static bool s24_get(size_t x) {
  return (s24)[((s24_idx) + (x)) % ((size_t)(1))];
}

static bool s23_get(size_t x) {
  return (s23)[((s23_idx) + (x)) % ((size_t)(1))];
}

static bool s22_get(size_t x) {
  return (s22)[((s22_idx) + (x)) % ((size_t)(1))];
}

static bool s21_get(size_t x) {
  return (s21)[((s21_idx) + (x)) % ((size_t)(1))];
}

static bool s20_get(size_t x) {
  return (s20)[((s20_idx) + (x)) % ((size_t)(1))];
}

static bool s19_get(size_t x) {
  return (s19)[((s19_idx) + (x)) % ((size_t)(1))];
}

static bool s18_get(size_t x) {
  return (s18)[((s18_idx) + (x)) % ((size_t)(1))];
}

static bool s17_get(size_t x) {
  return (s17)[((s17_idx) + (x)) % ((size_t)(1))];
}

static bool s16_get(size_t x) {
  return (s16)[((s16_idx) + (x)) % ((size_t)(1))];
}

static bool s15_get(size_t x) {
  return (s15)[((s15_idx) + (x)) % ((size_t)(1))];
}

static bool s14_get(size_t x) {
  return (s14)[((s14_idx) + (x)) % ((size_t)(1))];
}

static bool s13_get(size_t x) {
  return (s13)[((s13_idx) + (x)) % ((size_t)(1))];
}

static bool s12_get(size_t x) {
  return (s12)[((s12_idx) + (x)) % ((size_t)(1))];
}

static bool s11_get(size_t x) {
  return (s11)[((s11_idx) + (x)) % ((size_t)(1))];
}

static bool s10_get(size_t x) {
  return (s10)[((s10_idx) + (x)) % ((size_t)(1))];
}

static bool s9_get(size_t x) {
  return (s9)[((s9_idx) + (x)) % ((size_t)(1))];
}

static bool s8_get(size_t x) {
  return (s8)[((s8_idx) + (x)) % ((size_t)(1))];
}

static bool s7_get(size_t x) {
  return (s7)[((s7_idx) + (x)) % ((size_t)(1))];
}

static bool s6_get(size_t x) {
  return (s6)[((s6_idx) + (x)) % ((size_t)(1))];
}

static bool s5_get(size_t x) {
  return (s5)[((s5_idx) + (x)) % ((size_t)(1))];
}

static bool s4_get(size_t x) {
  return (s4)[((s4_idx) + (x)) % ((size_t)(1))];
}

static bool s3_get(size_t x) {
  return (s3)[((s3_idx) + (x)) % ((size_t)(1))];
}

static bool s2_get(size_t x) {
  return (s2)[((s2_idx) + (x)) % ((size_t)(1))];
}

static bool s1_get(size_t x) {
  return (s1)[((s1_idx) + (x)) % ((size_t)(1))];
}

static int32_t s61_get(size_t x) {
  return (s61)[((s61_idx) + (x)) % ((size_t)(1))];
}

static bool s62_get(size_t x) {
  return (s62)[((s62_idx) + (x)) % ((size_t)(1))];
}

static int32_t s63_get(size_t x) {
  return (s63)[((s63_idx) + (x)) % ((size_t)(1))];
}

static bool s64_get(size_t x) {
  return (s64)[((s64_idx) + (x)) % ((size_t)(1))];
}

/* Generator functions sN_gen(): compute next stream values as part of δ. */

static bool s0_gen(void) {
  return ((!(((battery_soc_cpy) > ((double)(0.8))) && ((!(obstacle_front_cpy)) && ((!(obstacle_left_cpy)) && ((!(obstacle_right_cpy)) && ((!(at_science_rock_cpy)) && (!(battery_near_outpost_cpy)))))))) || ((cmd_vel_lin_cpy) >= ((double)(2.0)))) && ((s0_get)((0)));
}

static bool s60_gen(void) {
  return ((battery_soc_cpy) <= ((double)(0.2))) && (!(battery_near_outpost_cpy));
}

static bool s59_gen(void) {
  return (s60_get)((0));
}

static bool s58_gen(void) {
  return (s59_get)((0));
}

static bool s57_gen(void) {
  return (s58_get)((0));
}

static bool s56_gen(void) {
  return (s57_get)((0));
}

static bool s55_gen(void) {
  return (s56_get)((0));
}

static bool s54_gen(void) {
  return (s55_get)((0));
}

static bool s53_gen(void) {
  return (s54_get)((0));
}

static bool s52_gen(void) {
  return (s53_get)((0));
}

static bool s51_gen(void) {
  return (s52_get)((0));
}

static bool s50_gen(void) {
  return (s51_get)((0));
}

static bool s49_gen(void) {
  return (s50_get)((0));
}

static bool s48_gen(void) {
  return (s49_get)((0));
}

static bool s47_gen(void) {
  return (s48_get)((0));
}

static bool s46_gen(void) {
  return (s47_get)((0));
}

static bool s45_gen(void) {
  return (s46_get)((0));
}

static bool s44_gen(void) {
  return (s45_get)((0));
}

static bool s43_gen(void) {
  return (s44_get)((0));
}

static bool s42_gen(void) {
  return (s43_get)((0));
}

static bool s41_gen(void) {
  return (s42_get)((0));
}

static bool s40_gen(void) {
  return (s41_get)((0));
}

static bool s39_gen(void) {
  return (s40_get)((0));
}

static bool s38_gen(void) {
  return (s39_get)((0));
}

static bool s37_gen(void) {
  return (s38_get)((0));
}

static bool s36_gen(void) {
  return (s37_get)((0));
}

static bool s35_gen(void) {
  return (s36_get)((0));
}

static bool s34_gen(void) {
  return (s35_get)((0));
}

static bool s33_gen(void) {
  return (s34_get)((0));
}

static bool s32_gen(void) {
  return (s33_get)((0));
}

static bool s31_gen(void) {
  return (s32_get)((0));
}

static bool s30_gen(void) {
  return (s31_get)((0));
}

static bool s29_gen(void) {
  return (s30_get)((0));
}

static bool s28_gen(void) {
  return (s29_get)((0));
}

static bool s27_gen(void) {
  return (s28_get)((0));
}

static bool s26_gen(void) {
  return (s27_get)((0));
}

static bool s25_gen(void) {
  return (s26_get)((0));
}

static bool s24_gen(void) {
  return (s25_get)((0));
}

static bool s23_gen(void) {
  return (s24_get)((0));
}

static bool s22_gen(void) {
  return (s23_get)((0));
}

static bool s21_gen(void) {
  return (s22_get)((0));
}

static bool s20_gen(void) {
  return (s21_get)((0));
}

static bool s19_gen(void) {
  return (s20_get)((0));
}

static bool s18_gen(void) {
  return (s19_get)((0));
}

static bool s17_gen(void) {
  return (s18_get)((0));
}

static bool s16_gen(void) {
  return (s17_get)((0));
}

static bool s15_gen(void) {
  return (s16_get)((0));
}

static bool s14_gen(void) {
  return (s15_get)((0));
}

static bool s13_gen(void) {
  return (s14_get)((0));
}

static bool s12_gen(void) {
  return (s13_get)((0));
}

static bool s11_gen(void) {
  return (s12_get)((0));
}

static bool s10_gen(void) {
  return (s11_get)((0));
}

static bool s9_gen(void) {
  return (s10_get)((0));
}

static bool s8_gen(void) {
  return (s9_get)((0));
}

static bool s7_gen(void) {
  return (s8_get)((0));
}

static bool s6_gen(void) {
  return (s7_get)((0));
}

static bool s5_gen(void) {
  return (s6_get)((0));
}

static bool s4_gen(void) {
  return (s5_get)((0));
}

static bool s3_gen(void) {
  return (s4_get)((0));
}

static bool s2_gen(void) {
  return (s3_get)((0));
}

static bool s1_gen(void) {
  return (s2_get)((0));
}

static int32_t s61_gen(void) {
  return ((s1_get)((0))) ? (int32_t)(1) : ((((s61_get)((0))) > ((int32_t)(0))) ? ((s61_get)((0))) - ((int32_t)(1)) : ((int32_t)(0)));
}

static bool s62_gen(void) {
  return false;
}

static int32_t s63_gen(void) {
  return (((s62_get)((0))) || (battery_near_outpost_cpy)) ? (int32_t)(60) : ((((s63_get)((0))) > ((int32_t)(0))) ? ((s63_get)((0))) - ((int32_t)(1)) : ((int32_t)(0)));
}

static bool s64_gen(void) {
  return ((!((((s1_get)((0))) ? (int32_t)(1) : ((((s61_get)((0))) > ((int32_t)(0))) ? ((s61_get)((0))) - ((int32_t)(1)) : ((int32_t)(0)))) > ((int32_t)(0)))) || (((((s62_get)((0))) || (battery_near_outpost_cpy)) ? (int32_t)(60) : ((((s63_get)((0))) > ((int32_t)(0))) ? ((s63_get)((0))) - ((int32_t)(1)) : ((int32_t)(0)))) > ((int32_t)(0)))) && ((s64_get)((0)));
}

/* Guard functions handler*_guard(): detect states in V and trigger monitor handlers. */

static bool handlerMR_011_MAINTAIN_SPEED_WHEN_FULL_BATTERY_0_guard(void) {
  return !(((!(((battery_soc_cpy) > ((double)(0.8))) && ((!(obstacle_front_cpy)) && ((!(obstacle_left_cpy)) && ((!(obstacle_right_cpy)) && ((!(at_science_rock_cpy)) && (!(battery_near_outpost_cpy)))))))) || ((cmd_vel_lin_cpy) >= ((double)(2.0)))) && ((s0_get)((0))));
}

static bool handlerMR_009_RETURN_TO_OUTPOST_ON_LOW_BATTERY_1_guard(void) {
  return !(((!((((s1_get)((0))) ? (int32_t)(1) : ((((s61_get)((0))) > ((int32_t)(0))) ? ((s61_get)((0))) - ((int32_t)(1)) : ((int32_t)(0)))) > ((int32_t)(0)))) || (((((s62_get)((0))) || (battery_near_outpost_cpy)) ? (int32_t)(60) : ((((s63_get)((0))) > ((int32_t)(0))) ? ((s63_get)((0))) - ((int32_t)(1)) : ((int32_t)(0)))) > ((int32_t)(0)))) && ((s64_get)((0))));
}

/* Global transition step(): copy inputs, evaluate guards, compute next state via sN_gen(), and update the streams. */

void step(void) {
  bool s0_tmp;
  bool s60_tmp;
  bool s59_tmp;
  bool s58_tmp;
  bool s57_tmp;
  bool s56_tmp;
  bool s55_tmp;
  bool s54_tmp;
  bool s53_tmp;
  bool s52_tmp;
  bool s51_tmp;
  bool s50_tmp;
  bool s49_tmp;
  bool s48_tmp;
  bool s47_tmp;
  bool s46_tmp;
  bool s45_tmp;
  bool s44_tmp;
  bool s43_tmp;
  bool s42_tmp;
  bool s41_tmp;
  bool s40_tmp;
  bool s39_tmp;
  bool s38_tmp;
  bool s37_tmp;
  bool s36_tmp;
  bool s35_tmp;
  bool s34_tmp;
  bool s33_tmp;
  bool s32_tmp;
  bool s31_tmp;
  bool s30_tmp;
  bool s29_tmp;
  bool s28_tmp;
  bool s27_tmp;
  bool s26_tmp;
  bool s25_tmp;
  bool s24_tmp;
  bool s23_tmp;
  bool s22_tmp;
  bool s21_tmp;
  bool s20_tmp;
  bool s19_tmp;
  bool s18_tmp;
  bool s17_tmp;
  bool s16_tmp;
  bool s15_tmp;
  bool s14_tmp;
  bool s13_tmp;
  bool s12_tmp;
  bool s11_tmp;
  bool s10_tmp;
  bool s9_tmp;
  bool s8_tmp;
  bool s7_tmp;
  bool s6_tmp;
  bool s5_tmp;
  bool s4_tmp;
  bool s3_tmp;
  bool s2_tmp;
  bool s1_tmp;
  int32_t s61_tmp;
  bool s62_tmp;
  int32_t s63_tmp;
  bool s64_tmp;
  (battery_soc_cpy) = (battery_soc);
  (obstacle_front_cpy) = (obstacle_front);
  (obstacle_left_cpy) = (obstacle_left);
  (obstacle_right_cpy) = (obstacle_right);
  (at_science_rock_cpy) = (at_science_rock);
  (battery_near_outpost_cpy) = (battery_near_outpost);
  (cmd_vel_lin_cpy) = (cmd_vel_lin);
  if ((handlerMR_011_MAINTAIN_SPEED_WHEN_FULL_BATTERY_0_guard)()) {
    {(handlerMR_011_MAINTAIN_SPEED_WHEN_FULL_BATTERY)();}
  };
  if ((handlerMR_009_RETURN_TO_OUTPOST_ON_LOW_BATTERY_1_guard)()) {
    {(handlerMR_009_RETURN_TO_OUTPOST_ON_LOW_BATTERY)();}
  };
  (s0_tmp) = ((s0_gen)());
  (s60_tmp) = ((s60_gen)());
  (s59_tmp) = ((s59_gen)());
  (s58_tmp) = ((s58_gen)());
  (s57_tmp) = ((s57_gen)());
  (s56_tmp) = ((s56_gen)());
  (s55_tmp) = ((s55_gen)());
  (s54_tmp) = ((s54_gen)());
  (s53_tmp) = ((s53_gen)());
  (s52_tmp) = ((s52_gen)());
  (s51_tmp) = ((s51_gen)());
  (s50_tmp) = ((s50_gen)());
  (s49_tmp) = ((s49_gen)());
  (s48_tmp) = ((s48_gen)());
  (s47_tmp) = ((s47_gen)());
  (s46_tmp) = ((s46_gen)());
  (s45_tmp) = ((s45_gen)());
  (s44_tmp) = ((s44_gen)());
  (s43_tmp) = ((s43_gen)());
  (s42_tmp) = ((s42_gen)());
  (s41_tmp) = ((s41_gen)());
  (s40_tmp) = ((s40_gen)());
  (s39_tmp) = ((s39_gen)());
  (s38_tmp) = ((s38_gen)());
  (s37_tmp) = ((s37_gen)());
  (s36_tmp) = ((s36_gen)());
  (s35_tmp) = ((s35_gen)());
  (s34_tmp) = ((s34_gen)());
  (s33_tmp) = ((s33_gen)());
  (s32_tmp) = ((s32_gen)());
  (s31_tmp) = ((s31_gen)());
  (s30_tmp) = ((s30_gen)());
  (s29_tmp) = ((s29_gen)());
  (s28_tmp) = ((s28_gen)());
  (s27_tmp) = ((s27_gen)());
  (s26_tmp) = ((s26_gen)());
  (s25_tmp) = ((s25_gen)());
  (s24_tmp) = ((s24_gen)());
  (s23_tmp) = ((s23_gen)());
  (s22_tmp) = ((s22_gen)());
  (s21_tmp) = ((s21_gen)());
  (s20_tmp) = ((s20_gen)());
  (s19_tmp) = ((s19_gen)());
  (s18_tmp) = ((s18_gen)());
  (s17_tmp) = ((s17_gen)());
  (s16_tmp) = ((s16_gen)());
  (s15_tmp) = ((s15_gen)());
  (s14_tmp) = ((s14_gen)());
  (s13_tmp) = ((s13_gen)());
  (s12_tmp) = ((s12_gen)());
  (s11_tmp) = ((s11_gen)());
  (s10_tmp) = ((s10_gen)());
  (s9_tmp) = ((s9_gen)());
  (s8_tmp) = ((s8_gen)());
  (s7_tmp) = ((s7_gen)());
  (s6_tmp) = ((s6_gen)());
  (s5_tmp) = ((s5_gen)());
  (s4_tmp) = ((s4_gen)());
  (s3_tmp) = ((s3_gen)());
  (s2_tmp) = ((s2_gen)());
  (s1_tmp) = ((s1_gen)());
  (s61_tmp) = ((s61_gen)());
  (s62_tmp) = ((s62_gen)());
  (s63_tmp) = ((s63_gen)());
  (s64_tmp) = ((s64_gen)());
  ((s0)[s0_idx]) = (s0_tmp);
  ((s60)[s60_idx]) = (s60_tmp);
  ((s59)[s59_idx]) = (s59_tmp);
  ((s58)[s58_idx]) = (s58_tmp);
  ((s57)[s57_idx]) = (s57_tmp);
  ((s56)[s56_idx]) = (s56_tmp);
  ((s55)[s55_idx]) = (s55_tmp);
  ((s54)[s54_idx]) = (s54_tmp);
  ((s53)[s53_idx]) = (s53_tmp);
  ((s52)[s52_idx]) = (s52_tmp);
  ((s51)[s51_idx]) = (s51_tmp);
  ((s50)[s50_idx]) = (s50_tmp);
  ((s49)[s49_idx]) = (s49_tmp);
  ((s48)[s48_idx]) = (s48_tmp);
  ((s47)[s47_idx]) = (s47_tmp);
  ((s46)[s46_idx]) = (s46_tmp);
  ((s45)[s45_idx]) = (s45_tmp);
  ((s44)[s44_idx]) = (s44_tmp);
  ((s43)[s43_idx]) = (s43_tmp);
  ((s42)[s42_idx]) = (s42_tmp);
  ((s41)[s41_idx]) = (s41_tmp);
  ((s40)[s40_idx]) = (s40_tmp);
  ((s39)[s39_idx]) = (s39_tmp);
  ((s38)[s38_idx]) = (s38_tmp);
  ((s37)[s37_idx]) = (s37_tmp);
  ((s36)[s36_idx]) = (s36_tmp);
  ((s35)[s35_idx]) = (s35_tmp);
  ((s34)[s34_idx]) = (s34_tmp);
  ((s33)[s33_idx]) = (s33_tmp);
  ((s32)[s32_idx]) = (s32_tmp);
  ((s31)[s31_idx]) = (s31_tmp);
  ((s30)[s30_idx]) = (s30_tmp);
  ((s29)[s29_idx]) = (s29_tmp);
  ((s28)[s28_idx]) = (s28_tmp);
  ((s27)[s27_idx]) = (s27_tmp);
  ((s26)[s26_idx]) = (s26_tmp);
  ((s25)[s25_idx]) = (s25_tmp);
  ((s24)[s24_idx]) = (s24_tmp);
  ((s23)[s23_idx]) = (s23_tmp);
  ((s22)[s22_idx]) = (s22_tmp);
  ((s21)[s21_idx]) = (s21_tmp);
  ((s20)[s20_idx]) = (s20_tmp);
  ((s19)[s19_idx]) = (s19_tmp);
  ((s18)[s18_idx]) = (s18_tmp);
  ((s17)[s17_idx]) = (s17_tmp);
  ((s16)[s16_idx]) = (s16_tmp);
  ((s15)[s15_idx]) = (s15_tmp);
  ((s14)[s14_idx]) = (s14_tmp);
  ((s13)[s13_idx]) = (s13_tmp);
  ((s12)[s12_idx]) = (s12_tmp);
  ((s11)[s11_idx]) = (s11_tmp);
  ((s10)[s10_idx]) = (s10_tmp);
  ((s9)[s9_idx]) = (s9_tmp);
  ((s8)[s8_idx]) = (s8_tmp);
  ((s7)[s7_idx]) = (s7_tmp);
  ((s6)[s6_idx]) = (s6_tmp);
  ((s5)[s5_idx]) = (s5_tmp);
  ((s4)[s4_idx]) = (s4_tmp);
  ((s3)[s3_idx]) = (s3_tmp);
  ((s2)[s2_idx]) = (s2_tmp);
  ((s1)[s1_idx]) = (s1_tmp);
  ((s61)[s61_idx]) = (s61_tmp);
  ((s62)[s62_idx]) = (s62_tmp);
  ((s63)[s63_idx]) = (s63_tmp);
  ((s64)[s64_idx]) = (s64_tmp);
  (s0_idx) = (((s0_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s60_idx) = (((s60_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s59_idx) = (((s59_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s58_idx) = (((s58_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s57_idx) = (((s57_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s56_idx) = (((s56_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s55_idx) = (((s55_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s54_idx) = (((s54_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s53_idx) = (((s53_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s52_idx) = (((s52_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s51_idx) = (((s51_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s50_idx) = (((s50_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s49_idx) = (((s49_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s48_idx) = (((s48_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s47_idx) = (((s47_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s46_idx) = (((s46_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s45_idx) = (((s45_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s44_idx) = (((s44_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s43_idx) = (((s43_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s42_idx) = (((s42_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s41_idx) = (((s41_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s40_idx) = (((s40_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s39_idx) = (((s39_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s38_idx) = (((s38_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s37_idx) = (((s37_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s36_idx) = (((s36_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s35_idx) = (((s35_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s34_idx) = (((s34_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s33_idx) = (((s33_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s32_idx) = (((s32_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s31_idx) = (((s31_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s30_idx) = (((s30_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s29_idx) = (((s29_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s28_idx) = (((s28_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s27_idx) = (((s27_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s26_idx) = (((s26_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s25_idx) = (((s25_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s24_idx) = (((s24_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s23_idx) = (((s23_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s22_idx) = (((s22_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s21_idx) = (((s21_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s20_idx) = (((s20_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s19_idx) = (((s19_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s18_idx) = (((s18_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s17_idx) = (((s17_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s16_idx) = (((s16_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s15_idx) = (((s15_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s14_idx) = (((s14_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s13_idx) = (((s13_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s12_idx) = (((s12_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s11_idx) = (((s11_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s10_idx) = (((s10_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s9_idx) = (((s9_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s8_idx) = (((s8_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s7_idx) = (((s7_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s6_idx) = (((s6_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s5_idx) = (((s5_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s4_idx) = (((s4_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s3_idx) = (((s3_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s2_idx) = (((s2_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s1_idx) = (((s1_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s61_idx) = (((s61_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s62_idx) = (((s62_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s63_idx) = (((s63_idx) + ((size_t)(1))) % ((size_t)(1)));
  (s64_idx) = (((s64_idx) + ((size_t)(1))) % ((size_t)(1)));
}
