// Auto-generated by RiTMOS (manually patched)
//
// This patch fixes integration issues with the *actual* ROS topic/message types
// in your application, and avoids false violations caused by missing data.
//
// ======================= WHAT CHANGED (high level) =======================
// CHANGE 1) Use std_msgs/msg/Float32 for /battery/soc (your app publishes Float32).
//           The previous wrapper subscribed to Float64, so battery_soc stayed at 0.0.
//           That can spuriously trigger MR_009 and latch a violation.
//
// CHANGE 2) Subscribe to /cmd_vel (geometry_msgs/msg/Twist) and extract:
//             cmd_vel_lin = Twist.linear.x
//             cmd_vel_ang = Twist.angular.z
//           The previous wrapper subscribed to /cmd_vel_lin and /cmd_vel_ang topics,
//           which do not exist in your app.
//
// CHANGE 3) Remove subscription to /delta_yaw_deg (topic does not exist in your app).
//           We keep the Copilot global 'delta_yaw_deg' (because copilot.c declares it),
//           but we leave it at 0.0. (Not used by MR_009/MR_011.)
//
// CHANGE 4) Gate step() until we have received initial samples for critical inputs
//           (battery_soc, battery_near_outpost, cmd_vel). This prevents startup-time
//           false positives before the first messages arrive.
//
// CHANGE 5) Fix handler dispatch: remove CuriosityMonitor::instance() that created a
//           *second* Node. Handlers now dispatch to the node instance being spun.
//
// ========================================================================

#include <functional>
#include <memory>
#include <cstdint>
#include <string>
#include <chrono>
#include <type_traits>
#include <stdexcept>

#include "rclcpp/rclcpp.hpp"
#include "std_msgs/msg/string.hpp"

#include "copilot_types.h"

using std::placeholders::_1;

#include "std_msgs/msg/bool.hpp"
#include "std_msgs/msg/float32.hpp"          // CHANGE 1: Float32 for /battery/soc
#include "geometry_msgs/msg/twist.hpp"       // CHANGE 2: Twist for /cmd_vel

extern "C" {
// ===== Copilot "extern" inputs (declared by copilot.c) =====
bool obstacle_front = false;
bool obstacle_left = false;
bool obstacle_right = false;
bool at_science_rock = false;
bool battery_near_outpost = false;
double battery_soc = 0.0;
double cmd_vel_lin = 0.0;
double cmd_vel_ang = 0.0;
double delta_yaw_deg = 0.0; // CHANGE 3: no topic; kept at 0.0

void step(void);

// Only two handlers remain (per your reduced spec)
void handlerMR_011_MAINTAIN_SPEED_WHEN_FULL_BATTERY(void);
void handlerMR_009_RETURN_TO_OUTPOST_ON_LOW_BATTERY(void);
}

// Only bool mapping is used now (numeric topics are handled explicitly)
template<typename T> struct RosMsg { using type = void; };
template<> struct RosMsg<bool>     { using type = std_msgs::msg::Bool;     };

class CuriosityMonitor : public rclcpp::Node {
public:
  CuriosityMonitor() : Node("curiosity_monitor") {
    // CHANGE 5: ensure handler dispatch uses the *running* node (no hidden 2nd Node)
    g_self = this;

    // Use SensorDataQoS for sim-like topics (best-effort friendly)
    const auto qos = rclcpp::SensorDataQoS();

    // ---- Bool topics (these exist in your app) ----
    {
      using MsgT = typename RosMsg<bool>::type;
      obstacle_front_sub_ = this->create_subscription<MsgT>(
        "/obstacle/front", qos, std::bind(&CuriosityMonitor::on_obstacle_front, this, _1));
    }
    {
      using MsgT = typename RosMsg<bool>::type;
      obstacle_left_sub_ = this->create_subscription<MsgT>(
        "/obstacle/left", qos, std::bind(&CuriosityMonitor::on_obstacle_left, this, _1));
    }
    {
      using MsgT = typename RosMsg<bool>::type;
      obstacle_right_sub_ = this->create_subscription<MsgT>(
        "/obstacle/right", qos, std::bind(&CuriosityMonitor::on_obstacle_right, this, _1));
    }
    {
      using MsgT = typename RosMsg<bool>::type;
      at_science_rock_sub_ = this->create_subscription<MsgT>(
        "/at_science_rock", qos, std::bind(&CuriosityMonitor::on_at_science_rock, this, _1));
    }
    {
      using MsgT = typename RosMsg<bool>::type;
      battery_near_outpost_sub_ = this->create_subscription<MsgT>(
        "/battery/near_outpost", qos, std::bind(&CuriosityMonitor::on_battery_near_outpost, this, _1));
    }

    // CHANGE 1: /battery/soc is Float32 in your application.
    //           We cast to double for the Copilot global.
    battery_soc_sub_ = this->create_subscription<std_msgs::msg::Float32>(
      "/battery/soc", qos, std::bind(&CuriosityMonitor::on_battery_soc, this, _1));

    // CHANGE 2: /cmd_vel is Twist in your application (no /cmd_vel_lin or /cmd_vel_ang topics).
    cmd_vel_sub_ = this->create_subscription<geometry_msgs::msg::Twist>(
      "/cmd_vel", qos, std::bind(&CuriosityMonitor::on_cmd_vel, this, _1));

    // Publishers for events + the two remaining handlers
    events_pub_ = this->create_publisher<std_msgs::msg::String>("monitor/events", 10);
    pub_handlerMR_011_MAINTAIN_SPEED_WHEN_FULL_BATTERY_ =
      this->create_publisher<std_msgs::msg::Bool>("monitor/handlerMR_011_MAINTAIN_SPEED_WHEN_FULL_BATTERY", 10);
    pub_handlerMR_009_RETURN_TO_OUTPOST_ON_LOW_BATTERY_ =
      this->create_publisher<std_msgs::msg::Bool>("monitor/handlerMR_009_RETURN_TO_OUTPOST_ON_LOW_BATTERY", 10);

    // CHANGE 4: Gate step() until required inputs have at least one sample.
    // This prevents "battery_soc = 0.0" (default) from arming MR_009 at startup.
    timer_ = this->create_wall_timer(
      std::chrono::milliseconds(1000),
      [this]() {
        if (!got_battery_soc_ || !got_battery_near_outpost_ || !got_cmd_vel_) {
          return; // silently wait (requested: no debug prints)
        }
        step();
      }
    );
  }

  // CHANGE 5: Handler dispatch uses the running node instance.
  static CuriosityMonitor& instance() {
    if (!g_self) {
      throw std::runtime_error("CuriosityMonitor not initialized yet");
    }
    return *g_self;
  }

  // ---- Handler methods (unchanged behavior; only two remain) ----
  void on_handlerMR_011_MAINTAIN_SPEED_WHEN_FULL_BATTERY() {
    publish_violation("handlerMR_011_MAINTAIN_SPEED_WHEN_FULL_BATTERY",
                      pub_handlerMR_011_MAINTAIN_SPEED_WHEN_FULL_BATTERY_);
  }
  void on_handlerMR_009_RETURN_TO_OUTPOST_ON_LOW_BATTERY() {
    publish_violation("handlerMR_009_RETURN_TO_OUTPOST_ON_LOW_BATTERY",
                      pub_handlerMR_009_RETURN_TO_OUTPOST_ON_LOW_BATTERY_);
  }

private:
  // Publish helper (keeps handlers consistent)
  void publish_violation(const char* name,
                         const rclcpp::Publisher<std_msgs::msg::Bool>::SharedPtr& pub) {
    RCLCPP_ERROR(this->get_logger(), "[Copilot] %s fired.", name);
    auto b = std_msgs::msg::Bool{}; b.data = true;
    pub->publish(b);

    auto s = std_msgs::msg::String{};
    s.data = std::string("VIOLATION: ") + name;
    events_pub_->publish(s);
  }

  // ---- Topic callbacks ----
  void on_obstacle_front(const std_msgs::msg::Bool::SharedPtr m) { obstacle_front = m->data; }
  void on_obstacle_left(const std_msgs::msg::Bool::SharedPtr m)  { obstacle_left = m->data; }
  void on_obstacle_right(const std_msgs::msg::Bool::SharedPtr m) { obstacle_right = m->data; }
  void on_at_science_rock(const std_msgs::msg::Bool::SharedPtr m){ at_science_rock = m->data; }

  void on_battery_near_outpost(const std_msgs::msg::Bool::SharedPtr m) {
    battery_near_outpost = m->data;
    got_battery_near_outpost_ = true; // CHANGE 4: readiness gating
  }

  // CHANGE 1: Float32 subscription for battery_soc
  void on_battery_soc(const std_msgs::msg::Float32::SharedPtr m) {
    battery_soc = static_cast<double>(m->data);
    got_battery_soc_ = true; // CHANGE 4: readiness gating
  }

  // CHANGE 2: Twist subscription for cmd_vel
  void on_cmd_vel(const geometry_msgs::msg::Twist::SharedPtr m) {
    cmd_vel_lin = static_cast<double>(m->linear.x);
    cmd_vel_ang = static_cast<double>(m->angular.z);
    got_cmd_vel_ = true; // CHANGE 4: readiness gating
  }

private:
  // CHANGE 4: readiness flags
  bool got_battery_soc_{false};
  bool got_battery_near_outpost_{false};
  bool got_cmd_vel_{false};

  // Subscriptions
  rclcpp::Subscription<std_msgs::msg::Bool>::SharedPtr obstacle_front_sub_;
  rclcpp::Subscription<std_msgs::msg::Bool>::SharedPtr obstacle_left_sub_;
  rclcpp::Subscription<std_msgs::msg::Bool>::SharedPtr obstacle_right_sub_;
  rclcpp::Subscription<std_msgs::msg::Bool>::SharedPtr at_science_rock_sub_;
  rclcpp::Subscription<std_msgs::msg::Bool>::SharedPtr battery_near_outpost_sub_;
  rclcpp::Subscription<std_msgs::msg::Float32>::SharedPtr battery_soc_sub_;              // CHANGE 1
  rclcpp::Subscription<geometry_msgs::msg::Twist>::SharedPtr cmd_vel_sub_;                // CHANGE 2

  // Publishers
  rclcpp::Publisher<std_msgs::msg::String>::SharedPtr events_pub_;
  rclcpp::Publisher<std_msgs::msg::Bool>::SharedPtr pub_handlerMR_011_MAINTAIN_SPEED_WHEN_FULL_BATTERY_;
  rclcpp::Publisher<std_msgs::msg::Bool>::SharedPtr pub_handlerMR_009_RETURN_TO_OUTPOST_ON_LOW_BATTERY_;
  rclcpp::TimerBase::SharedPtr timer_;

  // CHANGE 5: running instance pointer for handler dispatch.
  static CuriosityMonitor* g_self;
};

// static member definition
CuriosityMonitor* CuriosityMonitor::g_self = nullptr;

// Copilot handler entrypoints (must remain extern "C")
extern "C" void handlerMR_011_MAINTAIN_SPEED_WHEN_FULL_BATTERY(void) {
  CuriosityMonitor::instance().on_handlerMR_011_MAINTAIN_SPEED_WHEN_FULL_BATTERY();
}
extern "C" void handlerMR_009_RETURN_TO_OUTPOST_ON_LOW_BATTERY(void) {
  CuriosityMonitor::instance().on_handlerMR_009_RETURN_TO_OUTPOST_ON_LOW_BATTERY();
}

int main(int argc, char* argv[]) {
  rclcpp::init(argc, argv);
  rclcpp::spin(std::make_shared<CuriosityMonitor>());
  rclcpp::shutdown();
  return 0;
}
