"""
ritmos_exporter.py
──────────────────
Exports the two artifacts required by RiTMOS for monitor synthesis:

  1. ``signals_full.yaml`` — variable/signal mapping
  2. ``roverSpec_full.fcs`` — FRETish requirements specification

If canonical RiTMOS schema documentation becomes available, this module
should be updated to match exactly.  The current format is based on the
FRET/FRETish conventions documented in NASA FRET publications.
"""

from __future__ import annotations

from pathlib import Path
from typing import List, Optional

from .fretish_writer import Requirement, requirements_to_fcs
from .variable_mapper import VariableMap, variable_map_to_signals_yaml


def export_ritmos_artifacts(
    reqs: List[Requirement],
    vmap: VariableMap,
    output_dir: Path,
    signals_filename: str = "signals_full.yaml",
    spec_filename: str = "roverSpec_full.fcs",
) -> dict:
    """
    Write both RiTMOS artifacts to ``output_dir``.

    Returns a dict with paths and any warnings.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    signals_path = output_dir / signals_filename
    spec_path = output_dir / spec_filename

    # ── signals_full.yaml ─────────────────────────────────────────
    signals_content = variable_map_to_signals_yaml(vmap)
    signals_path.write_text(signals_content)

    # ── roverSpec_full.fcs ────────────────────────────────────────
    # Header comment
    header = (
        "// roverSpec_full.fcs\n"
        "// Generated by SpaceTry FRETish Agent\n"
        "//\n"
        "// Format: FRETish Compact Specification for RiTMOS monitor synthesis\n"
        "// Each requirement block:\n"
        "//   // REQ_ID (kind) — description\n"
        "//   <FRETish natural-language requirement>\n"
        "//\n\n"
    )
    fcs_content = header + requirements_to_fcs(reqs)
    spec_path.write_text(fcs_content)

    # ── Warnings ──────────────────────────────────────────────────
    warnings = []
    if vmap.has_unmapped():
        warnings.append(
            f"WARNING: {len(vmap.unmapped)} unmapped signal(s) — "
            "signals_full.yaml may be incomplete."
        )
    unverified_in_map = [
        mv.name
        for mv in vmap.all_mapped().values()
        if not mv.verified
    ]
    if unverified_in_map:
        warnings.append(
            f"WARNING: {len(unverified_in_map)} unverified signal(s) in map: "
            f"{', '.join(unverified_in_map)}"
        )

    return {
        "signals_path": str(signals_path),
        "spec_path": str(spec_path),
        "warnings": warnings,
    }
