-- Generated by RiTMOS
-- Implements: ptltl_H, ptltl_Y, ptltl_Z, ptltl_S, ptltl_O, ptltl_Ow
-- and low-level primitives used by the pretty-printer: historically, yesterday,
-- weakYesterday, since, once, countdown, prevB/prevI, rise/fall.

module Copilot.PtLTL where

import qualified Copilot.Language as C

-- ========== Signal Helpers ==========
-- Previous (B: Boolean, I: Int32)
prevB :: Bool -> C.Stream Bool -> C.Stream Bool
prevB init s = [init] C.++ s

prevI :: C.Int32 -> C.Stream C.Int32 -> C.Stream C.Int32
prevI init s = [init] C.++ s

-- Rising or Falling Edge
rise :: C.Stream Bool -> C.Stream Bool
rise s = s C.&& C.not (prevB False s)

fall :: C.Stream Bool -> C.Stream Bool
fall s = (prevB False s) C.&& C.not s

-- ========== ptLTL primitives ==========
-- Historically (H)
historically :: C.Stream Bool -> C.Stream Bool
historically p = r where r = p C.&& prevB True r

-- Yesterday (Y) and Weak-Yesterday (Z)
yesterday :: C.Stream Bool -> C.Stream Bool
yesterday p = prevB False p

weakYesterday :: C.Stream Bool -> C.Stream Bool
weakYesterday p = prevB True p

-- Since (S):  b S a
since :: C.Stream Bool -> C.Stream Bool -> C.Stream Bool
since b a = r where r = b C.|| (a C.&& prevB False r)

-- Once (O) unbounded
once :: C.Stream Bool -> C.Stream Bool
once p = r where r = p C.|| prevB False r

-- Countdown that stays > 0 for exactly n ticks after 'start'.
countdown :: C.Int32 -> C.Stream Bool -> C.Stream Bool
countdown n start = cnt C.> C.constant 0
  where
    cnt :: C.Stream C.Int32
    cnt = C.mux start (C.constant n)
            (C.mux ((prevI 0 cnt) C.> C.constant 0)
                   ((prevI 0 cnt) C.- C.constant 1)
                   (C.constant 0))

-- ========= Wrappers used by codegen =========
ptltl_H :: C.Stream Bool -> C.Stream Bool
ptltl_H = historically

ptltl_Y :: C.Stream Bool -> C.Stream Bool
ptltl_Y = yesterday

ptltl_Z :: C.Stream Bool -> C.Stream Bool
ptltl_Z = weakYesterday

ptltl_S :: C.Stream Bool -> C.Stream Bool -> C.Stream Bool
ptltl_S = since

ptltl_O :: C.Stream Bool -> C.Stream Bool
ptltl_O = once

-- Once with bounded window [lo,hi]; assumes 0 <= lo <= hi
ptltl_Ow :: Int -> Int -> C.Stream Bool -> C.Stream Bool
ptltl_Ow lo hi a
  | lo < 0 || hi < 0 || lo > hi = error "ptltl_Ow: invalid window"
  | lo == 0   = countdown (fromIntegral (hi + 1)) a
  | otherwise = countdown (fromIntegral (hi - lo + 1)) (shiftN lo a)

-- Shift a stream back by n steps using Y
shiftN :: Int -> C.Stream Bool -> C.Stream Bool
shiftN n s | n <= 0    = s
           | otherwise = shiftN (n - 1) (yesterday s)
