frame: world
waypoints:
  outpost_habitat_01:
    x: 66.0
    y: 0.0
    yaw: 3.07
    tolerance: 1.0

  science_rock_01:
    x: 50.10
    y: -80.0
    yaw: 3.07
    tolerance: 1.0

  ridge:
    x: 12.0
    y: 4.0
    yaw: 0.0
    tolerance: 1.0

  safe_haven:
    x: -5.0
    y: -5.0
    yaw: 0.0
    tolerance: 1.0
