frame: world
waypoints:
  outpost_habitat_01:
    x: 66.0
    y: 0.0
    yaw: 3.07
    tolerance: 1.0

  science_rock_01:
    x: 50.10
    y: -80.0
    yaw: 3.07
    tolerance: 1.0

  dock_pad_01:
    x: 0.0
    y: 0.0
    yaw: 0.0
    tolerance: 1.0

